---
- name: "install node.js from node scource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs

    sudo npm install -g n
    sudo n 13.8.0

- name: "install node.js lts using apt"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "install pm2 globally"
  npm:
    name: pm2
    global: yes
